export {
  PILL_INSET,
  SNAP_IN,
  SNAP_OUT,
  centerOnWorkArea,
  clamp,
  closestSnap,
  compactAnchorFromBounds,
  compactSize,
  edgeDistances,
  emptyPanelSize,
  fitInWork,
  isCornerDock,
  isHorizontalDock,
  isSideDock,
  panelSize,
  pillSizeForWindow,
  positionForSize,
  resolveDock,
  sizeForMode,
  toastSize,
} from "../shared/layout.js";
